export const ActionTypes = {
  ADD_TODO_TO_TODOS_LIST: "ADD_TODO_TO_TODOS_LIST",
  SET_TO_TODOS_LIST: "SET_TO_TODOS_LIST",
  SET_TO_COMPLETED_TODOS_LIST: "SET_TO_COMPLETED_TODOS_LIST",
  SET_TO_IN_PROGRESS_TODOS_LIST: "SET_TO_IN_PROGRESS_TODOS_LIST",
  SET_TODO: "SET_TODO",
  REMOVE_SELECTED_TODO: "REMOVE_SELECTED_TODO",
};
